<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLN9xTLH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLN9xTLH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLN9xTLH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLN9xTLH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLN9xTLH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LN9xTLH',
    'container.build_id' => 'b7dfa738',
    'container.build_time' => 1565001735,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLN9xTLH');
