<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.WpZKSt4' shared service.

return $this->privates['.service_locator.WpZKSt4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::compte' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\EntrepiseController::add' => ['privates', '.service_locator.6puk0Ru', 'get_ServiceLocator_6puk0RuService.php', true],
    'App\\Controller\\SecurityController::addcaisse' => ['privates', '.service_locator.6puk0Ru', 'get_ServiceLocator_6puk0RuService.php', true],
    'App\\Controller\\SecurityController::block' => ['privates', '.service_locator.g3AG1HS', 'get_ServiceLocator_G3AG1HSService.php', true],
    'App\\Controller\\SecurityController::dblock' => ['privates', '.service_locator.g3AG1HS', 'get_ServiceLocator_G3AG1HSService.php', true],
    'App\\Controller\\SecurityController::edit' => ['privates', '.service_locator.fPmj2Hu', 'get_ServiceLocator_FPmj2HuService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecurityController::show' => ['privates', '.service_locator.fPmj2Hu', 'get_ServiceLocator_FPmj2HuService.php', true],
    'App\\Controller\\TransactionController::transac' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\CompteController:compte' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\EntrepiseController:add' => ['privates', '.service_locator.6puk0Ru', 'get_ServiceLocator_6puk0RuService.php', true],
    'App\\Controller\\SecurityController:addcaisse' => ['privates', '.service_locator.6puk0Ru', 'get_ServiceLocator_6puk0RuService.php', true],
    'App\\Controller\\SecurityController:block' => ['privates', '.service_locator.g3AG1HS', 'get_ServiceLocator_G3AG1HSService.php', true],
    'App\\Controller\\SecurityController:dblock' => ['privates', '.service_locator.g3AG1HS', 'get_ServiceLocator_G3AG1HSService.php', true],
    'App\\Controller\\SecurityController:edit' => ['privates', '.service_locator.fPmj2Hu', 'get_ServiceLocator_FPmj2HuService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\SecurityController:show' => ['privates', '.service_locator.fPmj2Hu', 'get_ServiceLocator_FPmj2HuService.php', true],
    'App\\Controller\\TransactionController:transac' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
], [
    'App\\Controller\\CompteController::compte' => '?',
    'App\\Controller\\EntrepiseController::add' => '?',
    'App\\Controller\\SecurityController::addcaisse' => '?',
    'App\\Controller\\SecurityController::block' => '?',
    'App\\Controller\\SecurityController::dblock' => '?',
    'App\\Controller\\SecurityController::edit' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\SecurityController::show' => '?',
    'App\\Controller\\TransactionController::transac' => '?',
    'App\\Controller\\CompteController:compte' => '?',
    'App\\Controller\\EntrepiseController:add' => '?',
    'App\\Controller\\SecurityController:addcaisse' => '?',
    'App\\Controller\\SecurityController:block' => '?',
    'App\\Controller\\SecurityController:dblock' => '?',
    'App\\Controller\\SecurityController:edit' => '?',
    'App\\Controller\\SecurityController:register' => '?',
    'App\\Controller\\SecurityController:show' => '?',
    'App\\Controller\\TransactionController:transac' => '?',
]);
